# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer config -g github-oauth.github.com $GH_TOKEN

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install

script:
  - php ./test/run/runner.php